# Generated by Django 4.2.4 on 2024-03-21 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('preco_conforto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_economico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cidade_destino', models.CharField(max_length=100)),
                ('duracao', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(36), django.core.validators.MinValueValidator(0)])),
                ('poltrona', models.CharField(max_length=4, null=True)),
                ('leito', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
