# Generated by Django 4.2.4 on 2024-03-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_confort', models.CharField(max_length=15)),
                ('price_econ', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=3)),
                ('seat', models.CharField(max_length=4, null=True)),
                ('bed', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Viagem',
        ),
    ]
